// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydfwoeqtpswhavgolprn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkZndvZXF0cHN3aGF2Z29scHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Nzg5MzUsImV4cCI6MjA2MDI1NDkzNX0.ryYbFfF_z2M5sHHNsmB1OtcXA9ysnKrUr7w2VlweSLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);